Sal-Mal/salmal-be

.gitmodules
- #3 
- https://data-engineer-tech.tistory.com/20
서브 모듈 적용 후 CI & CD 어떻게 할지
=> infra: 서브모듈 등록

.gitmodules
=> fix: 서브모듈 수정

.gitmodules
=> fix: 서브모듈 위치 수정

.github/workflows/build-test.yml, .github/workflows/deploy.yml, appspec.yml, scripts/health_check.sh, scripts/run_new_was.sh, scripts/switch.sh, src/main/java/com/salmalteam/salmal/HealthCheckController.java
=> infra: CD 관련 스크립트 및 GitHub Actions Flow 추가

.github/workflows/build-test.yml, .github/workflows/deploy.yml, build.gradle, src/docs/asciidoc/index.adoc, src/main/java/com/salmalteam/salmal/application/auth/AuthService.java, src/main/java/com/salmalteam/salmal/domain/auth/LogoutAccessToken.java, src/main/java/com/salmalteam/salmal/domain/auth/TokenRepository.java, src/main/java/com/salmalteam/salmal/dto/request/LogoutRequest.java, src/main/java/com/salmalteam/salmal/infra/auth/LogoutAccessTokenRepository.java, src/main/java/com/salmalteam/salmal/infra/auth/TokenRepositoryImpl.java, src/main/java/com/salmalteam/salmal/presentation/auth/AuthController.java, src/test/java/com/salmalteam/salmal/domain/auth/TokenRepositoryTest.java, src/test/java/com/salmalteam/salmal/presentation/auth/AuthControllerTest.java
=> feat: 로그아웃 기능 구현

src/docs/asciidoc/index.adoc, src/main/java/com/salmalteam/salmal/application/auth/AuthService.java, src/main/java/com/salmalteam/salmal/application/auth/TokenProvider.java, src/main/java/com/salmalteam/salmal/application/member/MemberService.java, src/main/java/com/salmalteam/salmal/dto/request/auth/LoginRequest.java, src/main/java/com/salmalteam/salmal/dto/request/auth/LogoutRequest.java, src/main/java/com/salmalteam/salmal/dto/request/auth/ReissueTokenRequest.java, src/main/java/com/salmalteam/salmal/dto/request/auth/SignUpRequest.java, src/main/java/com/salmalteam/salmal/dto/response/auth/LoginResponse.java, src/main/java/com/salmalteam/salmal/dto/response/auth/TokenResponse.java, src/main/java/com/salmalteam/salmal/exception/auth/AuthExceptionType.java, src/main/java/com/salmalteam/salmal/infra/auth/JwtProvider.java, src/main/java/com/salmalteam/salmal/presentation/auth/AuthController.java, src/test/java/com/salmalteam/salmal/application/auth/AuthServiceTest.java, src/test/java/com/salmalteam/salmal/application/member/MemberServiceTest.java, src/test/java/com/salmalteam/salmal/presentation/auth/AuthControllerTest.java
=> feat: 접근 토큰 재발급 기능 구현

src/docs/asciidoc/index.adoc, src/main/java/com/salmalteam/salmal/application/vote/VoteService.java, src/main/java/com/salmalteam/salmal/domain/member/bookmark/BookMarkVoteRepository.java, src/main/java/com/salmalteam/salmal/domain/vote/bookmark/VoteBookMark.java, src/main/java/com/salmalteam/salmal/domain/vote/bookmark/VoteBookMarkRepository.java, src/main/java/com/salmalteam/salmal/dto/request/vote/VoteBookmarkRequest.java, src/main/java/com/salmalteam/salmal/presentation/vote/VoteController.java, src/test/java/com/salmalteam/salmal/application/vote/VoteServiceTest.java, src/test/java/com/salmalteam/salmal/presentation/vote/VoteControllerTest.java
=> feat: 투표 북마킹 기능 구현

src/docs/asciidoc/index.adoc, src/main/java/com/salmalteam/salmal/application/vote/VoteService.java, src/main/java/com/salmalteam/salmal/domain/vote/report/VoteReport.java, src/main/java/com/salmalteam/salmal/domain/vote/report/VoteReportRepository.java, src/main/java/com/salmalteam/salmal/exception/vote/VoteExceptionType.java, src/main/java/com/salmalteam/salmal/presentation/vote/VoteController.java, src/test/java/com/salmalteam/salmal/application/vote/VoteServiceTest.java, src/test/java/com/salmalteam/salmal/presentation/vote/VoteControllerTest.java
=> feat: 투표 신고 기능 구현

src/docs/asciidoc/index.adoc, src/main/java/com/salmalteam/salmal/application/comment/CommentService.java, src/main/java/com/salmalteam/salmal/application/vote/VoteService.java, src/main/java/com/salmalteam/salmal/domain/vote/comment/Comment.java, src/main/java/com/salmalteam/salmal/domain/vote/comment/CommentRepository.java, src/main/java/com/salmalteam/salmal/dto/request/vote/VoteCommentUpdateRequest.java, src/main/java/com/salmalteam/salmal/presentation/comment/CommentController.java, src/main/java/com/salmalteam/salmal/presentation/vote/VoteController.java, src/test/java/com/salmalteam/salmal/application/comment/CommentServiceTest.java, src/test/java/com/salmalteam/salmal/presentation/comment/CommentControllerTest.java, src/test/java/com/salmalteam/salmal/support/PresentationTest.java
=> feat: 댓글 수정 기능 구현

src/docs/asciidoc/index.adoc
=> docs: API 문서 수정

src/main/java/com/salmalteam/salmal/domain/member/Introduction.java
=> fix: 회원 한 줄 소개 길이 관련 예외 수정

src/docs/asciidoc/index.adoc, src/main/java/com/salmalteam/salmal/application/member/MemberService.java, src/main/java/com/salmalteam/salmal/domain/member/MemberRepositoryCustomImpl.java, src/main/java/com/salmalteam/salmal/domain/member/block/BlockMemberRepository.java, src/main/java/com/salmalteam/salmal/domain/member/block/MemberBlocked.java, src/main/java/com/salmalteam/salmal/domain/member/block/MemberBlockedRepository.java, src/main/java/com/salmalteam/salmal/exception/member/block/MemberBlockedException.java, src/main/java/com/salmalteam/salmal/exception/member/block/MemberBlockedExceptionType.java, src/main/java/com/salmalteam/salmal/presentation/member/MemberController.java, src/test/java/com/salmalteam/salmal/application/member/MemberServiceTest.java, src/test/java/com/salmalteam/salmal/presentation/member/MemberControllerTest.java, src/test/java/com/salmalteam/salmal/presentation/vote/VoteControllerTest.java
=> feat: 회원 차단 & 차단 취소 기능 구현

src/docs/asciidoc/index.adoc, src/main/java/com/salmalteam/salmal/application/comment/CommentService.java, src/main/java/com/salmalteam/salmal/domain/comment/report/CommentReportRepository.java, src/main/java/com/salmalteam/salmal/presentation/comment/CommentController.java, src/test/java/com/salmalteam/salmal/application/comment/CommentServiceTest.java, src/test/java/com/salmalteam/salmal/presentation/comment/CommentControllerTest.java
=> feat: 댓글 신고 기능 구현

src/docs/asciidoc/index.adoc, src/main/java/com/salmalteam/salmal/application/comment/CommentService.java, src/main/java/com/salmalteam/salmal/application/member/MemberService.java, src/main/java/com/salmalteam/salmal/domain/member/Member.java, src/main/java/com/salmalteam/salmal/domain/vote/Vote.java, src/main/java/com/salmalteam/salmal/dto/request/member/MemberImageUpdateRequest.java, src/main/java/com/salmalteam/salmal/dto/request/member/MyPageUpdateRequest.java, src/main/java/com/salmalteam/salmal/presentation/member/MemberController.java, src/test/java/com/salmalteam/salmal/application/member/MemberServiceTest.java, src/test/java/com/salmalteam/salmal/domain/member/MemberTest.java, src/test/java/com/salmalteam/salmal/presentation/member/MemberControllerTest.java
=> feat: 마이페이지 수정 & 회원 이미지 수정 기능 구현

src/main/java/com/salmalteam/salmal/application/member/MemberService.java
=> fix: 마이페이지 수정 시 닉네임까지 변경해야하는 문제 수정

src/main/java/com/salmalteam/salmal/application/vote/VoteService.java, src/main/java/com/salmalteam/salmal/domain/vote/bookmark/VoteBookMarkRepository.java, src/main/java/com/salmalteam/salmal/exception/vote/bookmark/VoteBookmarkException.java, src/main/java/com/salmalteam/salmal/exception/vote/bookmark/VoteBookmarkExceptionType.java, src/test/java/com/salmalteam/salmal/application/vote/VoteServiceTest.java
=> fix: 북마크 중복 요청 시 예외 발생시키도록 변경

src/docs/asciidoc/index.adoc, src/main/java/com/salmalteam/salmal/application/member/MemberService.java, src/main/java/com/salmalteam/salmal/domain/vote/VoteRepositoryCustom.java, src/main/java/com/salmalteam/salmal/domain/vote/VoteRepositoryCustomImpl.java, src/main/java/com/salmalteam/salmal/dto/request/member/vote/MemberBookmarkVotePageRequest.java, src/main/java/com/salmalteam/salmal/dto/response/member/vote/MemberBookmarkVotePageResponse.java, src/main/java/com/salmalteam/salmal/dto/response/member/vote/MemberBookmarkVoteResponse.java, src/main/java/com/salmalteam/salmal/dto/response/member/vote/MemberEvaluationVotePageResponse.java, src/main/java/com/salmalteam/salmal/presentation/member/MemberController.java, src/test/java/com/salmalteam/salmal/presentation/member/MemberControllerTest.java
=> feat: 회원 북마크 투표 목록 조회 기능 구현

src/main/java/com/salmalteam/salmal/domain/vote/VoteRepositoryCustomImpl.java
=> fix: 투표 목록 조회 시 북마킹 여부 제대로 표기 안되는 문제 해결

src/main/java/com/salmalteam/salmal/application/comment/CommentService.java
=> fix: 대댓글 목록 조회 API 동작안하는 문제 해결

src/main/java/com/salmalteam/salmal/domain/vote/VoteRepositoryCustom.java, src/main/java/com/salmalteam/salmal/domain/vote/VoteRepositoryCustomImpl.java
=> fix: 회원 북마크 목록 조회 시 북마크한 투표 리스트를 제대로 가져오지 못하는 문제 해결

src/main/java/com/salmalteam/salmal/domain/vote/VoteRepositoryCustomImpl.java
=> fix: 투표 목록 HOME 타입 커서 기반 페이지네이션 첫 조회 안되는 문제 해결

src/main/java/com/salmalteam/salmal/domain/image/ImageFile.java, src/test/java/com/salmalteam/salmal/domain/image/ImageFileTest.java
=> fix: 이미지 업로더 지원 확장자 추가

src/main/java/com/salmalteam/salmal/application/member/MemberService.java, src/main/java/com/salmalteam/salmal/domain/member/MemberImage.java, src/main/java/com/salmalteam/salmal/presentation/member/MemberController.java, src/test/java/com/salmalteam/salmal/presentation/member/MemberControllerTest.java
=> feat: 회원 프로필 삭제 기능 구현

src/docs/asciidoc/index.adoc
=> docs: 회원 프로필 삭제 API 문서화

src/main/java/com/salmalteam/salmal/application/EventHandler.java, src/main/java/com/salmalteam/salmal/application/comment/CommentService.java, src/main/java/com/salmalteam/salmal/application/vote/VoteService.java, src/main/java/com/salmalteam/salmal/domain/comment/Comment.java, src/main/java/com/salmalteam/salmal/domain/comment/CommentRepository.java, src/main/java/com/salmalteam/salmal/domain/comment/like/CommentLikeRepository.java, src/main/java/com/salmalteam/salmal/domain/member/Member.java, src/main/java/com/salmalteam/salmal/domain/vote/Vote.java, src/main/java/com/salmalteam/salmal/domain/vote/VoteRepository.java, src/main/java/com/salmalteam/salmal/domain/vote/evaluation/VoteEvaluationRepository.java
- #126 
- #127 
- #128 
- #129 
- #130
=> fix: 회원 탈퇴 시 일어나는 다양한 문제점들 수정

src/main/java/com/salmalteam/salmal/application/auth/AuthService.java, src/main/java/com/salmalteam/salmal/dto/response/auth/TokenAvailableResponse.java, src/main/java/com/salmalteam/salmal/presentation/auth/AuthController.java, src/test/java/com/salmalteam/salmal/application/auth/AuthServiceTest.java, src/test/java/com/salmalteam/salmal/presentation/auth/AuthControllerTest.java
- #24 
토큰 검증 API 구현했습니다.
api 단위 테스트 작성하면서 rest docs 반영했는데 한번 확인해주시면 감사합니다 -> [1f867e9](https://github.com/Sal-Mal/salmal-be/pull/140/commits/1f867e983bf36fb0bb974464537e2b05eba2caf2)
- **노션 API docs 확인** https://honorable-overcoat-a54.notion.site/2de76f516ac245078b8e5fcb8a93e5d9
=> Feature: 토큰 정보 확인(토큰 유효성 검사) API 구현

src/main/java/com/salmalteam/salmal/presentation/config/WebConfig.java
=> fix: health check api 인증인터셉터 제외

src/main/java/com/salmalteam/salmal/auth/infrastructure/RefreshTokenProvider.java, src/test/java/com/salmalteam/salmal/auth/infrastructure/RefreshTokenProviderTest.java
=> Fix/payload 설정 순서 변경

src/docs/asciidoc/index.adoc
=> fix: 문서 오탈자 수정

src/main/java/com/salmalteam/salmal/member/entity/MemberImage.java
=> refactor: 기본 이미지 url 변경

src/main/java/com/salmalteam/salmal/comment/application/CommentService.java, src/main/java/com/salmalteam/salmal/vote/application/VoteService.java
- #176 
ID 값 비교가 재대로 되지않는것 같아서 우선적으로 변경 후 서버에서 재 테스트
=> Fix/정상적인 인증과정 후 댓글 삭제, 투표삭제 등 삭제권한이 없어 삭제가 되지않는 문제 해결

src/main/java/com/salmalteam/salmal/comment/application/CommentService.java
=> refactor/대댓글 생성시 투표의 댓글 수 증가하게 변경

src/main/java/com/salmalteam/salmal/comment/application/CommentService.java
=> Fix: 대댓글 삭제 시 투표 전체 댓글 수 감소하게 수정

src/main/java/com/salmalteam/salmal/comment/application/CommentService.java, src/main/java/com/salmalteam/salmal/vote/entity/VoteRepository.java
=> fix: jpa type 에러, 엔티티 lazy 조회 이슈 해결

src/main/java/com/salmalteam/salmal/comment/application/CommentService.java, src/main/java/com/salmalteam/salmal/comment/entity/CommentRepository.java, src/main/java/com/salmalteam/salmal/vote/entity/VoteRepository.java
=> Fix: 삭제로직 재수정

src/main/java/com/salmalteam/salmal/vote/entity/report/VoteReportRepositoryCustomImpl.java
=> fix: from 절 추가

src/docs/asciidoc/index.adoc, src/main/java/com/salmalteam/salmal/presentation/http/vote/VoteController.java, src/main/java/com/salmalteam/salmal/vote/application/VoteService.java, src/main/java/com/salmalteam/salmal/vote/dto/response/MemberVoteParticipantsDto.java, src/main/java/com/salmalteam/salmal/vote/dto/response/VoteParticipantsResponse.java, src/main/java/com/salmalteam/salmal/vote/entity/evaluation/VoteEvaluationCustom.java, src/main/java/com/salmalteam/salmal/vote/entity/evaluation/VoteEvaluationCustomImpl.java, src/main/java/com/salmalteam/salmal/vote/entity/evaluation/VoteEvaluationRepository.java, src/test/java/com/salmalteam/salmal/config/DataJpaTestConfig.java, src/test/java/com/salmalteam/salmal/presentation/http/vote/VoteControllerTest.java, src/test/java/com/salmalteam/salmal/vote/entity/evaluation/VoteEvaluationRepositoryTest.java
=> Feature: vote participants api

src/main/java/com/salmalteam/salmal/vote/entity/evaluation/VoteEvaluationCustomImpl.java
=> fix: 참여자 조회 조인쿼리 변경

docker/Dockerfile, docker/docker-compose.dev.yaml
=> chore: 도커파일, 도커컴포즈 작성, dev 브랜치 생성 후 추가수정 예정

scripts/cd_dev_jenkinsfile
* chore: jenkinsfile 작성
* chore: Clean up docker image 삭제
=> Feature/infra GitHub (#201)
